// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again:
// With a Flutter package, run `flutter pub run build_runner build`.
// With a Dart package, run `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart';
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'HabitDB.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <ModelEntity>[
  ModelEntity(
      id: const IdUid(1, 7443487625560928004),
      name: 'HabitDB',
      lastPropertyId: const IdUid(3, 3526207951852985145),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 8277054436421663407),
            name: 'id',
            type: 6,
            flags: 1),
        ModelProperty(
            id: const IdUid(2, 693507857914496154),
            name: 'habit',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(3, 3526207951852985145),
            name: 'date',
            type: 10,
            flags: 0)
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[]),
  ModelEntity(
      id: const IdUid(2, 5837135603960526587),
      name: 'HabitList',
      lastPropertyId: const IdUid(2, 1328187163489215219),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 8535232702747533823),
            name: 'id',
            type: 6,
            flags: 1),
        ModelProperty(
            id: const IdUid(2, 1328187163489215219),
            name: 'habit',
            type: 9,
            flags: 0)
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[])
];

/// Open an ObjectBox store with the model declared in this file.
Future<Store> openStore(
        {String? directory,
        int? maxDBSizeInKB,
        int? fileMode,
        int? maxReaders,
        bool queriesCaseSensitiveDefault = true,
        String? macosApplicationGroup}) async =>
    Store(getObjectBoxModel(),
        directory: directory ?? (await defaultStoreDirectory()).path,
        maxDBSizeInKB: maxDBSizeInKB,
        fileMode: fileMode,
        maxReaders: maxReaders,
        queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
        macosApplicationGroup: macosApplicationGroup);

/// ObjectBox model definition, pass it to [Store] - Store(getObjectBoxModel())
ModelDefinition getObjectBoxModel() {
  final model = ModelInfo(
      entities: _entities,
      lastEntityId: const IdUid(2, 5837135603960526587),
      lastIndexId: const IdUid(0, 0),
      lastRelationId: const IdUid(0, 0),
      lastSequenceId: const IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [],
      retiredPropertyUids: const [],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, EntityDefinition>{
    HabitDB: EntityDefinition<HabitDB>(
        model: _entities[0],
        toOneRelations: (HabitDB object) => [],
        toManyRelations: (HabitDB object) => {},
        getId: (HabitDB object) => object.id,
        setId: (HabitDB object, int id) {
          object.id = id;
        },
        objectToFB: (HabitDB object, fb.Builder fbb) {
          final habitOffset = fbb.writeString(object.habit);
          fbb.startTable(4);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, habitOffset);
          fbb.addInt64(2, object.date.millisecondsSinceEpoch);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = HabitDB(
              id: const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0),
              habit: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 6, ''),
              date: DateTime.fromMillisecondsSinceEpoch(
                  const fb.Int64Reader().vTableGet(buffer, rootOffset, 8, 0)));

          return object;
        }),
    HabitList: EntityDefinition<HabitList>(
        model: _entities[1],
        toOneRelations: (HabitList object) => [],
        toManyRelations: (HabitList object) => {},
        getId: (HabitList object) => object.id,
        setId: (HabitList object, int id) {
          object.id = id;
        },
        objectToFB: (HabitList object, fb.Builder fbb) {
          final habitOffset = fbb.writeString(object.habit);
          fbb.startTable(3);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, habitOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = HabitList(
              id: const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0),
              habit: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 6, ''));

          return object;
        })
  };

  return ModelDefinition(model, bindings);
}

/// [HabitDB] entity fields to define ObjectBox queries.
class HabitDB_ {
  /// see [HabitDB.id]
  static final id = QueryIntegerProperty<HabitDB>(_entities[0].properties[0]);

  /// see [HabitDB.habit]
  static final habit = QueryStringProperty<HabitDB>(_entities[0].properties[1]);

  /// see [HabitDB.date]
  static final date = QueryIntegerProperty<HabitDB>(_entities[0].properties[2]);
}

/// [HabitList] entity fields to define ObjectBox queries.
class HabitList_ {
  /// see [HabitList.id]
  static final id = QueryIntegerProperty<HabitList>(_entities[1].properties[0]);

  /// see [HabitList.habit]
  static final habit =
      QueryStringProperty<HabitList>(_entities[1].properties[1]);
}
